services:
  # ==== Serviço da API ====
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxy-agent
    restart: unless-stopped
    # use uv run (ou remova esta linha para usar o CMD do Dockerfile)
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"