# docker-compose.yml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxy-agent
    restart: unless-stopped
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      DB_URI: ${DB_URI}
      UV_LINK_MODE: "copy"
    # A secção 'volumes' foi completamente removida para garantir que
    # o container é 100% baseado na imagem construída.
    ports:
      - "8000:8000"