name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Chave SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Adicionar Host SSH aos hosts conhecidos
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Executar Script de Deploy na VM
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            # 1. Navega para o diretório do projeto
            cd proxy-agent

            # 2. Força a sincronização com o repositório remoto
            git fetch origin
            git reset --hard origin/main
            
            # 3. Para e remove os containers antigos (sem sudo)
            docker compose down

            # 4. Reconstrói a imagem sem cache (sem sudo)
            docker compose build --no-cache

            # 5. Inicia os novos containers (sem sudo)
            docker compose up -d
          EOF